### ISSUE TITLE
Cmd Glow not working

### ISSUE THREAD

**Issue by jeffom** [Broxxar/GlowingObjectOutlines#1] opened 2017-04-12 20:50 UTC
I cloned the repository and tried to play the cmd_buffer_variant scene, all objects names were empty and I couldnt play the scene right after cloning.
So after setting up the mats and scene i tried to play it but it only showed a purple blur ( i think that the texture was not set correctly to for the blurr ), could I have more instructions about the configuration of the scene and the glow controller to make my scene work?

**Comment by Broxxar** [comment] 2017-04-12 21:10
Sounds like an issue with files not getting checked in or serialized properly, I'll double check what a fresh clone of the repo looks like on my end.

Also which version of Unity are you using?

**Comment by jeffom** [comment] 2017-04-12 21:12
Hi, I'm using Unity 5.3.5p7

**Comment by jeffom** [comment] 2017-04-12 21:35
Also I tried to build the scene using an iOS device, but the glowing effect just stays white and it only shows on the cylinder, do you know why?

**Comment by Broxxar** [comment] 2017-04-12 21:37
Can't speak to how this would work on mobile. The code uses Mouse Enter/Exit messages and wasn't intended to use out-of-box on mobile.

**Comment by jeffom** [comment] 2017-04-12 21:40
I modified the GlowObject to always show the glow

**Comment by Broxxar** [comment] 2017-04-19 05:12
The project will only open properly in Unity versions 5.5 or later. Confirmed that objects names appear blank and scene does not function in Unity 5.3 , because presumably Unity does not support backwards compatibility.

Closing this issue.

**Closed as completed by Broxxar** 2017-04-19 05:12 UTC
